import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import { useSession, signIn, signOut, getSession } from "next-auth/react";
import { SignupCont } from "../../components/styles/common.styled";
import PreLoad from "../../components/common/preLoad";
import { useEffect } from "react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Shop Manager | Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/img/logo.png" />
      </Head>
      <PreLoad />
      <Login />
    </>
  );
}

function Login() {
  const { data: session } = useSession();
  const router = useRouter();

  useEffect(() => {
    function gotoSignup() {
      router.push("/home");
    }

    if (session) {
      gotoSignup();
    }
  });

  return (
    <div className="login-body">
      <form className="form1">
        <div className="logo-container for-login">
          <div className="logo-container-1st-div">
            <Image
              className="chobi"
              src="/img/logo.png"
              width={60}
              height={60}
              alt="logo"
            />
          </div>

          <div className="logo-container-2nd-div">
            <h1 className="txt-c">Shop Manager</h1>
            <p className="txt-c deep txt-left">Make It Easy!</p>
          </div>
        </div>

        <SignupCont className="signup-btn">
          <button
            onClick={(e) => {
              e.preventDefault();
              signIn();
            }}
          >
            start managing
          </button>
        </SignupCont>
      </form>
    </div>
  );
}

export const getServerSideProps = async (context) => {
  const session = await getSession(context);

  return {
    props: { session },
  };
};
