import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/img/logo.png" />
      </Head>
      <Login />
    </>
  );
}

function Login() {
  return (
    <div className="login-body">
      <form className="form1">
        <div className="logo-container">
          <div className="logo-container-1st-div">
            <Image
              className="chobi"
              src="/img/logo.png"
              width={60}
              height={60}
              alt="logo"
            />
          </div>
          <div className="logo-container-2nd-div">
            <h2 className="txt-c">Shop Manager</h2>
            <p className="txt-c deep txt-left">Make It Easy!</p>
          </div>
        </div>

        <br />

        <input type="text" placeholder="Shop's Name" required />
        <input type="number" placeholder="Phone Number" required />
        <div className="remember">
          <input type="checkbox" required />
          <label> Remember me </label>
        </div>

        <input className="log-in-01" type="submit" value="Login" />
      </form>

      <div className="register">
        <p>
          Don't have an account?<Link href="./signup">Register</Link>
        </p>
      </div>
    </div>
  );
}
