import Head from "next/head";
import Navbar from "../../../components/common/navbar";
import styled from "@emotion/styled";
import { useSession, signIn, signOut, getSession } from "next-auth/react";
import { useRouter } from "next/router";
import { useEffect } from "react";
import PreLoad from "../../../components/common/preLoad";

const BodyContainer = styled.div`
  width: 100%;
  height: 100vh;
`;

const Home = () => {
  return (
    <>
      <Head>
        <title>Shop Manager | Store Management</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/img/logo.png" />
      </Head>
      <Body />
    </>
  );
};

function Body() {
  const router = useRouter();
  const { data: session } = useSession();
  console.log(session);

  useEffect(() => {
    function gotoSignup() {
      router.push("/");
    }

    if (!session) {
      gotoSignup();
    }
  });

  return (
    <BodyContainer>
      <PreLoad load="true" />
      <Navbar pos="4" />
    </BodyContainer>
  );
}

export default Home;
