import Head from "next/head";
import { useRouter } from "next/router";
import styled from "styled-components";
import Navbar from "./navbar";

const DetailsBodyContainer = styled.div`
  width: 100%;
  height: 100vh;
`;
const CustomerDetailsContainer = styled.div`
  width: 100%;
  display: flex;
  flex-direction: row;
  justify-content: center;

  div {
    width: 80%;
  }
`;

const Details = () => {
  return (
    <>
      <Head>
        <title>Shop Manager | Details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/img/logo.png" />
      </Head>
      <DetailsBody />
    </>
  );
};

function DetailsBody() {
  return (
    <DetailsBodyContainer>
      <Navbar />
      <CustomerDetails />
    </DetailsBodyContainer>
  );
}

function CustomerDetails() {
  let router = useRouter();
  let { id } = router.query;
  let parsedId = JSON.parse(id);
  let { name, phoneNumber, date, catagory } = parsedId;

  return (
    <CustomerDetailsContainer>
      <div>
        <div className="back-icon-container"></div>
        <div className="details-div">
          <p>Name: {name}</p>
          <p>Phone Number: {phoneNumber}</p>
          <p>Date: {date}</p>
          <p>Catagory: {catagory}</p>
        </div>
      </div>
    </CustomerDetailsContainer>
  );
}

export default Details;
