import Head from "next/head";
import { useRouter } from "next/router";
import styled from "styled-components";
import Navbar from "./navbar";

const server = "https://temporaryshopmanagerapi.onrender.com";

const DetailsBodyContainer = styled.div`
  width: 100%;
  height: 100vh;
`;
const CustomerDetailsContainer = styled.div`
  width: 100%;
  display: flex;
  flex-direction: row;
  justify-content: center;

  div {
    width: 80%;
  }
`;

export const getStaticPaths = async function () {
  let tableDataRes = await fetch(`${server}/api/home/tabledata`);
  let tableDataData = await tableDataRes.json();

  let paths = tableDataData.map((itm, i) => {
    return {
      params: { id: i.toString() },
    };
  });

  return {
    paths,
    fallback: false,
  };
};

export const getStaticProps = async function (context) {
  let id = context.params.id;

  let tableDataRes = await fetch(`${server}/api/home/tabledata/${id}`);
  let tableDataData = await tableDataRes.json();

  let { data } = tableDataData;

  return {
    props: { itm: data },
  };
};

const Index = ({ itm }) => {
  return (
    <>
      <Head>
        <title>Shop Manager | Details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/img/logo.png" />
      </Head>
      <DetailsBody itm={itm} />
    </>
  );
};

function DetailsBody({ itm }) {
  return (
    <DetailsBodyContainer>
      <Navbar />
      <CustomerDetails itm={itm} />
    </DetailsBodyContainer>
  );
}

function CustomerDetails({ itm }) {
  let { name, phoneNumber, date, catagory } = itm;

  return (
    <CustomerDetailsContainer>
      <div>
        <div className="back-icon-container"></div>
        <div className="details-div">
          <p>Name: {name}</p>
          <p>Phone Number: {phoneNumber}</p>
          <p>Date: {date}</p>
          <p>Catagory: {catagory}</p>
        </div>
      </div>
    </CustomerDetailsContainer>
  );
}

export default Index;
