import Head from "next/head";
import Navbar from "../../../components/common/navbar";
import styled from "@emotion/styled";
import AddCustomerData from "../../../components/createstorenewpage/AddCustomerData";
import { useSession, signIn, signOut, getSession } from "next-auth/react";
import { useRouter } from "next/router";
import PreLoad from "../../../components/common/preLoad";

const BodyContainer = styled.div`
  width: 100%;
  height: 100vh;
`;

const Home = () => {
  return (
    <>
      <Head>
        <title>Shop Manager | Create New Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/img/logo.png" />
      </Head>
      <Body />
    </>
  );
};

function Body() {
  const router = useRouter();
  const { data: session } = useSession();

  function gotoSignup() {
    router.push("/");
  }

  if (!session) {
    gotoSignup();
  }

  return (
    <BodyContainer>
      <PreLoad load="true" />
      <Navbar pos="2" />
      <AddCustomerData />
    </BodyContainer>
  );
}

export default Home;
