import Link from "next/link";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import Return_only_number from "../../js/Return_only_number";

const Signup = () => {
  let [nid_number, set_nid_number] = useState("");

  function handleKeyup(e) {
    let x = Return_only_number(e.target.value);
    e.target.value = x;

    set_nid_number(x);
  }

  return (
    <>
      <Head>
        <title>Signup</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/img/logo.png" />
      </Head>

      <div className="signup-body">
        <form className="form1">
          <div className="txt-c-01 for-sign-up">
            <div>
              <Image
                className="chobi"
                src="/img/logo.png"
                width={60}
                height={60}
                alt="logo"
              />
            </div>

            <div>
              <h1 className="create-txt-h1">Create a new account</h1>
              <p className="deep">Your secret our prority.</p>
            </div>
          </div>

          <input type="text" placeholder="Shop's Name" required />
          <div style={{ display: "flex" }} className="names-container">
            <span>
              <input
                type="text"
                placeholder="First name"
                required
                style={{ width: "100%" }}
              />
            </span>

            <span>
              <input
                type="text"
                placeholder="Surname"
                required
                style={{ width: "100%" }}
              />
            </span>
          </div>

          <input type="text" placeholder="Address" required />
          <input
            type="text"
            placeholder="NID Number"
            required
            onKeyUp={(e) => {
              handleKeyup(e);
            }}
          />
          <input type="text" placeholder="Email Address" required />
          <input
            type="text"
            placeholder="Phone Number"
            required
            onKeyUp={(e) => {
              handleKeyup(e);
            }}
          />

          <p className="gender-p">
            <input type="radio" name="Gender" id="Male" />
            <label htmlFor="Male">Male</label>
            <input type="radio" name="Gender" id="Female" />
            <label htmlFor="Female">Female</label>
            <input type="radio" name="Gender" id="Custom" />
            <label htmlFor="Custom">Custom</label>
          </p>

          <div className="checkbox-container">
            <input type="checkbox" required />
            <p>
              By clicking this, you agree to our Terms & conditions.You may
              receive SMS notifications from us and can opt out at any time.
            </p>
          </div>

          <input className="log-in" type="submit" value="Register" />
        </form>

        <p className="already-acccount-class">
          Already have an Account!
          <Link href="./">Login</Link>
        </p>
      </div>
    </>
  );
};

export default Signup;
