import Link from "next/link";
import Head from "next/head";

const Signup = () => {
  return (
    <>
      <Head>
        <title>Signup</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/img/logo.png" />
      </Head>

      <div class="signup-body">
        <form class="form1">
          <div class="txt-c-01">
            <h1 class="create-txt-h1">Create a new account</h1>
            <p class="deep">Your secret our prority.</p>
          </div>

          <br />

          <input type="text" placeholder="Shop's Name" required />
          <p style={{ display: "flex" }} class="names-container">
            <span>
              <input
                type="text"
                placeholder="First name"
                required
                style={{ width: "100%" }}
              />
            </span>
            <span>
              <input
                type="text"
                placeholder="Surname"
                required
                style={{ width: "100%" }}
              />
            </span>
          </p>

          <input type="text" placeholder="Address" required />
          <input type="number" placeholder="NID Number" required />
          <input type="text" placeholder="Email Address" required />
          <input type="number" placeholder="Phone Number" required />

          <p class="gender-p">
            <input type="radio" name="Gender" id="Male" />
            <label for="Male">Male</label>
            <input type="radio" name="Gender" id="Female" />
            <label for="Female">Female</label>
            <input type="radio" name="Gender" id="Custom" />
            <label for="Custom">Custom</label>
          </p>
          <div class="checkbox-container">
            <input type="checkbox" required />
            <p>
              By clicking this, you agree to our Terms & conditions.You may
              receive SMS notifications from us and can opt out at any time.
            </p>
          </div>
          <br />
          <input class="log-in" type="submit" value="Register" />
        </form>

        <p class="already-acccount-class">
          Already have an Account!
          <Link href="./">Login</Link>
        </p>
      </div>
    </>
  );
};

export default Signup;
