import Head from "next/head";
import Navbar from "../../../components/common/navbar";
import styled from "@emotion/styled";
import { useSession, signIn, signOut, getSession } from "next-auth/react";
import { useEffect } from "react";
import { useRouter } from "next/router";
import PreLoad from "../../../components/common/preLoad";

const BodyContainer = styled.div`
  width: 100%;
  height: 100vh;
`;

const Home = () => {
  return (
    <>
      <Head>
        <title>Shop Manager | Settings</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/img/logo.png" />
      </Head>
      <Body />
    </>
  );
};

function Body() {
  const { data: session } = useSession();
  const router = useRouter();

  useEffect(() => {
    function gotoSignup() {
      router.push("/");
    }

    if (!session) {
      gotoSignup();
    }
  });

  return (
    <BodyContainer>
      <PreLoad load="true" />
      <Navbar pos="5" />

      <div style={{ width: "100%", display: "flex", justifyContent: "center" }}>
        <div style={{ width: "80%" }}>
          {session && (
            <>
              <p>{session.user.email}</p>
              <p>{session.user.name}</p>
              <p>
                <img
                  src={session.user.image}
                  alt="google-account-image"
                  style={{ borderRadius: "50px" }}
                />
              </p>

              <button
                onClick={() => {
                  signOut();
                }}
              >
                signOut
              </button>
            </>
          )}
        </div>
      </div>
    </BodyContainer>
  );
}

export default Home;

export const getServerSideProps = async (context) => {
  const session = await getSession(context);

  return {
    props: { session },
  };
};
